# Generated by Django 3.1.12 on 2026-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_auto_20251108_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='aadhar_number',
        ),
        migrations.AddField(
            model_name='license',
            name='education',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
