# Generated by Django 3.1.12 on 2026-02-09 11:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20251108_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/blog/', location='C:\\Users\\ADMIN\\Desktop\\New folder (10)\\NPF\\server\\dmm_backend\\static\\blog'), upload_to=''),
        ),
    ]
