# Generated by Django 3.1.12 on 2026-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20251108_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
